apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - redirect-middleware.yaml
  # ClusterIssuers and Certificates will be applied after CRDs are installed
  # Uncomment after cert-manager is running:
  # - clusterissuer.yaml
  # - certificates.yaml
