apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-smartbiz
  namespace: smartbiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-smartbiz
  template:
    metadata:
      labels:
        app: cloudflared-smartbiz
    spec:
      containers:
      - name: cloudflared
        image: erisamoe/cloudflared:latest
        args:
        - tunnel
        - --url
        - http://smartbiz-ui.smartbiz.svc.cluster.local:80
        - --no-autoupdate
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
