apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartbiz-ui
  namespace: smartbiz
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - smartbiz.local
    secretName: smartbiz-tls-secret
  rules:
  - host: smartbiz.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartbiz-ui
            port:
              number: 80
