apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartbiz-ui
  namespace: smartbiz
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: smartbiz.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smartbiz-ui
            port:
              number: 80
