apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - nginx-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - cloudflared-deployment.yaml
