apiVersion: v1
kind: Service
metadata:
  name: smartbiz-ui
  namespace: smartbiz
  labels:
    app: smartbiz-ui
spec:
  selector:
    app: smartbiz-ui
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP
