---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  namespace: kafka-demo
spec:
  selector:
    app: kafka-producer
  ports:
  - port: 8000
    name: metrics
    targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-orders
  namespace: kafka-demo
spec:
  selector:
    app: kafka-consumer-orders
  ports:
  - port: 8001
    name: metrics
    targetPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-analytics
  namespace: kafka-demo
spec:
  selector:
    app: kafka-consumer-analytics
  ports:
  - port: 8002
    name: metrics
    targetPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-replay
  namespace: kafka-demo
spec:
  selector:
    app: kafka-consumer-replay
  ports:
  - port: 8003
    name: metrics
    targetPort: 8003
