apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: order-pipeline
resources:
  - namespace.yaml
  - sealed-secret.yaml
  - configmap.yaml
  - deployments.yaml
  - services.yaml
