---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: grafana
spec:
  encryptedData:
    admin-password: AgAyfA3hHJoWRGXAJgZwR9qNVL37BImTpi/uDh67ZRu09tBfgMmEhgOl7Ksvdm7/ZavjqyeyGITfah+HwdkGaxAwWo4l36RE2dNiV1KsaHDC9caV4j9oswafZS6agRsSb3CJpL6BECAaXomM8Na/MNt8K8Hsu44GbZnclgiv5ReZ9BdkCsUWZqyq7k1AmUpL4WaZdmssTQzJ1n/XxhDv+kxlamZ4KZ+RNEMT57zQ5XRyRQWPpird7uq0hepINKPVwlqpgheY4bnUjV0KiXL9oEAydRLrLoyEp5ykhrvT2SAC8P+C6uiKngLDIJe/9Jz0j0FBUvQJS5+junhiqbllHextfSB3cI1p3FThThKOA3WKLwPyxHARpG+rLLKbDw6zfa1lejcAlvRJax5Jy4Dex9Ux54vuOF7ar34PKiOVEA1ztiAyJP4i35UmSN+r+qbpPckFtr54eu+JJSQaIwsZmu2wX2ZDWKWXqu3dRH3KgdrBJsqEtXxxiJEbyZQGnNTLDCs0rtOOBL5Qrm8XFyH/W9SD0IAJvZhZ5yOFuKYTLsxWO0pCyMq4IteWIUMyQPswcvV8wBSTdsIO4liTFptnBJhuc8KnLNxCUgBJc5qzL6sQtJ2j1NRX1Z+7r4ZKq6m6uKrP783cvfnDoMSWdAPt05yauDd3b388INL4xNqjnjQQOfftHJgXXtjHq76s5Q5RP3iHDj3jIu1pRSKt+64ojwHCyzQ=
    admin-user: AgAzXl6eIZDtM/lYBIs9yy6s9ytONmWZ+0yshqYT9P1ygoyB/iFZ+7jXjRcsHmV6xIEu2pvmccvbQPx6x6y42Qy6k0rq70IDXHyBFIdSa572ICyRwRQzgrv+fjPgNm9EHWjEZMhdYu68f4Jl/IYsxoopnbKUmMJrk2c3xg6z52nKaeKCf2teFlJcWNaNvZpsL7FP8pUIPX/puFpEkblpaksLwEVCEjku1v3JSgHKqHfK2abBIkTkZBni7fofpIo6r4zTms8Uyas3WQ2eqv1TkIp5966S9TPATbggxeKKSUcneFlpBtTuIbEZ0G2hNZFiZtW459g4lXV+c5OHqOuiJU/LUTpajxS6D4UiOHyKXK7VzvOlaPVvAh6dKyRkWujXBT+jRiIAoGWgwqEfIHPUDm68RY86xXJB8yGYA9v0lygvGNNrCYxgN34IC7U4ysS6wmheeduaETOe7JtUM8QtLZMOnBdgHiCkYUcYg2mIvaCWi/m8WLxHw0QAKgHZiZC1mzApAzZBMZLq/gx1IdZZzbKLj6zLNgZilacl3dclUgXdtdcofoCmQ7Dh0rpCMzTwGya2nt5vPsU63xp55XQP4pfQZC2UIXLP38x4V+j1taLZq8NBWAVqTvqInWcF5ymxJP9nRyqYvKFP0nUuQAAAaxlrE5mO/EVlleiAeWNOWHBfKoDNwaXPCYvIdqTv5BxGkjTNDtFhQA==
  template:
    metadata:
      name: grafana-admin
      namespace: grafana
    type: Opaque
